from typing import Any, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator

# ---------------------------------------------------------------------------
# 1. DocumentProfile (Output of Triage Agent)
# ---------------------------------------------------------------------------

OriginType = Literal["scanned_image", "native_digital", "mixed"]
LayoutComplexity = Literal["single_column", "multi_column", "table_heavy"]


class DocumentProfile(BaseModel):
    """
    Profile representing the high-level classification of a document.
    Generated by the TriageAgent to route to the correct extraction strategy.
    """

    doc_id: str = Field(description="Unique identifier for the document")
    origin_type: OriginType = Field(description="Detected origin of the document")
    layout_complexity: LayoutComplexity = Field(description="Detected layout complexity")
    domain_hint: Optional[str] = Field(
        default=None, description="Hints like 'financial', 'tax', etc."
    )
    language: str = Field(default="en", description="Detected language")
    estimated_extraction_cost: float = Field(
        default=0.0, ge=0.0, description="Estimated USD cost to extract"
    )
    confidence_score: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Confidence in this profiling"
    )


# ---------------------------------------------------------------------------
# 2. ExtractedDocument (Unified Output of Extraction Routers)
# ---------------------------------------------------------------------------


class BBox(BaseModel):
    """Bounding box coordinates (x0, y0, x1, y1) in points."""

    x0: float
    y0: float
    x1: float
    y1: float

    @field_validator("x1")
    @classmethod
    def check_x_order(cls, v: float, info: Any) -> float:
        if "x0" in info.data and v < info.data["x0"]:
            raise ValueError("x1 must be greater than x0")
        return v

    @field_validator("y1")
    @classmethod
    def check_y_order(cls, v: float, info: Any) -> float:
        if "y0" in info.data and v < info.data["y0"]:
            raise ValueError("y1 must be greater than y0")
        return v


class ExtractedText(BaseModel):
    """A span of text with spatial provenance."""

    text: str
    page_number: int
    bbox: Optional[BBox] = None


class ExtractedTable(BaseModel):
    """A structured table extracted from the document."""

    markdown_grid: str = Field(description="Markdown representation of the table")
    page_number: int
    bbox: Optional[BBox] = None
    caption: Optional[str] = None


class ExtractedFigure(BaseModel):
    """An image or figure extracted from the document."""

    image_base64: Optional[str] = None
    file_path: Optional[str] = None
    caption: Optional[str] = None
    page_number: int
    bbox: Optional[BBox] = None


class ExtractedDocument(BaseModel):
    """
    Unified schema representing the full structured extraction of a document,
    regardless of whether it came from Strategy A, B, or C.
    """

    doc_id: str
    text_blocks: List[ExtractedText] = Field(default_factory=list)
    tables: List[ExtractedTable] = Field(default_factory=list)
    figures: List[ExtractedFigure] = Field(default_factory=list)
    strategy_used: Literal["A_FastText", "B_Layout", "C_Vision"]
    confidence_score: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Confidence in the extraction quality"
    )
    cost_estimate: float = Field(
        default=0.0, ge=0.0, description="Estimated USD cost for this extraction"
    )
    extraction_time_seconds: float = 0.0
    needs_human_review: bool = False


# ---------------------------------------------------------------------------
# 3. LDU: Logical Document Unit (Semantic Chunk)
# ---------------------------------------------------------------------------

ChunkType = Literal["paragraph", "table", "list", "figure", "section_header"]


class LDU(BaseModel):
    """
    A Logical Document Unit corresponding to a semantic chunk (e.g., a table,
    a paragraph, a list) ready for vectorization.
    """

    chunk_id: str
    doc_id: str
    content: str = Field(description="The actual text or markdown payload")
    chunk_type: ChunkType
    page_refs: List[int] = Field(description="Pages this chunk spans")
    bounding_box: Optional[BBox] = None

    # Relationships
    parent_section: Optional[str] = Field(
        default=None, description="Title of the section this belongs to"
    )
    cross_references: List[str] = Field(
        default_factory=list, description="IDs of other chunks referenced"
    )

    # Metadata
    token_count: int = 0
    content_hash: str = Field(
        description="SHA-256 hash of the content for deduplication/provenance"
    )


# ---------------------------------------------------------------------------
# 4. PageIndex (Hierarchical Navigation)
# ---------------------------------------------------------------------------


class PageIndexNode(BaseModel):
    """A node in the document's section tree."""

    section_id: str
    title: str
    page_start: int
    page_end: int
    level: int = Field(description="Header level (e.g. 1 for H1, 2 for H2)")
    summary: Optional[str] = Field(default=None, description="Concise LLM-generated summary")
    key_entities: List[str] = Field(default_factory=list)
    data_types_present: List[ChunkType] = Field(default_factory=list)
    children: List["PageIndexNode"] = Field(default_factory=list)

    @field_validator("page_end")
    @classmethod
    def check_page_range(cls, v: int, info: Any) -> int:
        if "page_start" in info.data and v < info.data["page_start"]:
            raise ValueError("page_end must be greater than or equal to page_start")
        return v


class PageIndex(BaseModel):
    """The hierarchical navigation tree for a full document."""

    doc_id: str
    root_nodes: List[PageIndexNode] = Field(default_factory=list)


# Allow circular/forward references in Pydantic models
PageIndexNode.model_rebuild()

# ---------------------------------------------------------------------------
# 5. ProvenanceChain (Audit Trail)
# ---------------------------------------------------------------------------


class ProvenanceCitation(BaseModel):
    """A single citation linking an extracted fact to its source."""

    document_name: str
    page_number: int
    bbox: Optional[BBox] = None
    content_hash: str = Field(description="Hash of the LDU this fact came from")
    excerpt: str = Field(description="Small snippet of the original text")


class ProvenanceChain(BaseModel):
    """An array of citations backing up an LLM-generated answer."""

    answer_text: str
    citations: List[ProvenanceCitation] = Field(default_factory=list)
    is_verified: bool = Field(default=False, description="Whether this has passed Audit Mode")
